---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-credentials
  namespace: openclaw
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgCOTJeylxn8HdiOgSKXooTEGA3pLmkNm6jbz4SXg8Lom8f5mhotMHV3/Uhv2++zxfZMrfkgFdvamw0AKsypHZN2rdZKBRO1hdV7giFEY5tmqj+FWdoucPFvhx2NCG4KuYWUn50pGwWl8yCYDzMkb2AtG1R5QvmHf4IFRYYKnlKnSegcvQ6NfeMOIUKyemUQgzlaCE8zIdY6esQZxCFoxKo9V+DVW/H1DqgS2Ae6I3rOBYBbdz/50DdpYZ1NAej9vOV7s0JEXcQpRQty5snH4uaLzMDuedjjqY4nP+owBu95wrn66C7wzAPVABkBDFWnAzEDZsdSe+CkB/FFC+1y55bFKtclVtsfhLsmPC3CQVVtlga0ReYpIqwFJPWfsx18YP1rWXwAsFviD376F/TRON4sVwUzKLg312ceKWOqWfl7XOcfnZ0z1yTN/kDLQeoyb858r3p5C3K+6RRjtKFPPM5ZAJqZNNz10j767cekKQa8n42aqkj36TKP85hpEHByOZTTXQH88GwbU/H1ilb5bAOsM6wF8ASGO9S8063X10jO8ciIC1yPN7p5Yn9nl3cawO6lNkr2ZYuvUaBbAaoCpAzaHWXEOqWPydOwskYi0GLXim34nKu4VVgQqqYpnOYmgguPwV9tk7Y2Ysh22n9mfzRs5Gb0EbPDqKBlI3FXEMeLnyZWFDr2rgzVQhL4THJYlhg07/rj8NEh06glhRMgyoW2ro9wT3Qr
    OPENCLAW_GATEWAY_TOKEN: AgBdmK+cBRgsNHjnlueW4m4+7M0fbZh6eHQFRhJ/cK7EI/C38EnOPcu0Zv1UpZvvldcpBP0jJtFRRVx6j5nFjM9LFGqimtIZW7wrYMXnqFxi5t++U8OPfwzDz5yjTTOF54YG6WN52CmLZnvNbAQpCvm5SWqvVjacp9VO4ENadVmK6EZcxkdW5ubQHq6CPmMpigGnDGtptEYcV/cSZDZf5r4BAp/XDc5kBASmsUF+WoaptgNE6VHXFbV/v97C1Z7c2uQGG1xulI6qg/XZfGKpSaLTUb1Mltk7iVi2b8MUrzgReN//MC2oJa/3F+11nLmwmcDBViOz3F8tXl3/Aczmp7/RPq65q/j5qJPAW4Rd35UQRzKASuhK+GnLLkPSkSYOR4mCuubjGwFKxYzMQEUKKpmeXC299TtCQBpSiJEyIpjomHAA70n97XLeP7O47pPR49Ni9RJbgS17DbN4aYHkiY57nOJAHRVfDD4Des0/YRd2gU8IWBETO9KLSv7q4Mnj/HBUgsasb4SjrLswxuptD6Tq4iAys+3B5oBx+PFOrANr4st6ja4CiGmgIlSstVmls2wxhqQsX88niwtPfd3p+JwaEhEWZXPcOjJeSTs5/BXx+twPKSpmqi21SMjNYCSozpqDuY4UBoUYijkxP41LQB/yHFxJvSoBD1Pdr5N3NNCMxSUscfLUcXPEcCAiHw67EJzkD3MtgqYyylSrE40s74ETMfMG8SE=
  template:
    metadata:
      name: openclaw-credentials
      namespace: openclaw
    type: Opaque
