# sealedsecret-ssh.yaml -- SealedSecret for SSH handshake secret.
#
# Re-seal with:
#   kubectl create secret generic openshell-ssh-handshake \
#     --from-literal=secret=$(openssl rand -hex 32) \
#     -n openshell --dry-run=client -o yaml \
#     | kubeseal --controller-namespace kube-system -o yaml \
#     > sealedsecret-ssh.yaml
#
# This value is sealed against the current cluster's sealing key.
# After make down/up, re-seal if the sealing key was not restored.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openshell-ssh-handshake
  namespace: openshell
spec:
  encryptedData:
    secret: AgB+1ocqSxqz3wXOYUd5mQsllO0QjdA7BxcsmFxyvqvPnwsbcYBZl+vd6qKIiHeEdRHkZLKDmatlhMM527Z5ZYi2RNH9qIF6+XGMEH2IN4kjAnUtl9P20czlCRBIbulXCwWcdTW0l9W/gZCWsoW8VTgFhO5+suIyUNKcdLCHeNnIMWMRBmdoC1HL6wRlc9JGn88rqX6ry+WhufAL0uIX0lQ1BHnh9Y2R97AE253duOm6q8GYOFNeluPckpGy+1WHVOvwiQljMmOMmMROWn/rkjNpYsfjtyiWcFqZK11G7YdcJOnItGlB8AUPMvrjuwgCrTWYh+wMWiYRd2i+CdWaOV4aIUvrvSVcB6Seot00jBDsBpowfPdIwZXC2AoHYhCdO9Fjwcgjt93tJ1WBgZglChmRGo7m39HcBBuf91FedBKY5/zme3UbRnkcXILAbUZF6OwqyWEDFF8rhulqZCC65TQHNyRl5It0kzwF3l19KMIRgrHlYSpO/GZoM78EmX/ee4yKT9gCXueOaECaOshhDsW5jL4EaaWg7r1zUf8xf3a5FE4p6BpsjyGXMIK/87JLy8HZyC6qIG6F5OdEMvmGZZU+eVTISgUucWO3DmFkkQfl6vuSHhk5r6WOlYx5/poH28bN7oBejlSsaJnT67nUAm8Ymkib4007J9rT6AnfFC8YgpeYPZQ1YR7tfnEBbW0b+ppxJG5zysDDzW40KoJvsXjc51Yk8yLLeKir3u9RldvbYJSJhiFRxcIr7sQrVseBHfZ2BEU8/A3pDIhmOUlH6pZE
  template:
    metadata:
      name: openshell-ssh-handshake
      namespace: openshell
