# sealedsecret-ssh.yaml -- SealedSecret for SSH handshake secret.
#
# Re-seal with:
#   kubectl create secret generic openshell-ssh-handshake \
#     --from-literal=secret=$(openssl rand -hex 32) \
#     -n openshell --dry-run=client -o yaml \
#     | kubeseal --controller-namespace kube-system -o yaml \
#     > sealedsecret-ssh.yaml
#
# This value is sealed against the current cluster's sealing key.
# After make down/up, re-seal if the sealing key was not restored.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openshell-ssh-handshake
  namespace: openshell
spec:
  encryptedData:
    secret: AgBz7ftXRmX/7hVfw/Yszi/4w2rD9NzxsoHxyzEI9WRr6duFRfQyDWY2uiFLRc1494v5VNcTsoDk9slxWMjMwy73Jus8iYFiGb0hQLlS5rbtmmsWCCj9042Ku4PvSf77S+gnFmRtcFFYrEvqFe3X21SpnJUF6AkAc3D+LVMoTif7hVtVEh1gvHxmohtfxAcYZHcsZPrdlLVq4fAmsG0RWfmBj+eHU3MMpAUyGHr6IEeDc8Bx/cxjntYV1nIuBz3FNIkhaN06utWx+x0krimotl/ljRCpcL7ujQ9mylbdKHZbfRfx2yKjR1xZdX+kj72idNCNujeSiKqx3zk1opFoaQQ+V0Dj1bEspeLdjd/FN7vQsmSvaCis65yMDMzDu2TSlYHrGFdqMNJ1hmvazdrVpIBggCi2lZxGq+giLVYLi3+qPA8DNSSzE0iw3q2nOX9Dz4iHS4ptUs7wmGY6aWGIFD8bygJxh20l/EokbNqjWt/tsjw0+MB38O/4ub2bi9nAD+LPi7rvWLs+06HTQssrhoAT2xwpSygmkXHQId1wZs/faxaDobAtBaG4RQsiy303xULx0h4JRPSqdy2J3qwQvpBZFCVhVADgMOuKtQigdgCKAzWZ6FnJY8R1VtYSYAYbM3U5p1hQDSw3/eAvyvIXHEibb8LX/aC/hdf3qi2jrg9z+h7toyU6rylYt2izRk66lyHDqZvc6qGbrLsQPWtSe/5K9P7EmTiKEL3g2Nyz146J82j+0MGW+WrSD09KpYK5UCmE4lCPCleV0SbemnTR7WKQ
  template:
    metadata:
      name: openshell-ssh-handshake
      namespace: openshell
